version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
  web:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    volumes:
      - .:/code
      - ipython:/root/.ipython
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DEBUG=True
    stdin_open: true
    tty: true

volumes:
  ipython:
